### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by mjgarton** [jonhoo/msql-srv#23]
Is there any interest in supporting SSL encrypted mysql connections?

I have added this locally for my own purposes, but it's a bit ugly at the moment.

If it's wanted, I'm happy to tidy it up and submit a PR.

**Comment by mjgarton** [comment]
See https://github.com/jonhoo/msql-srv/pull/26

**Comment by jonhoo** [comment]
There is very much interest in that indeed, thanks for submitting #26!

**Comment by mjgarton** [comment]
TLS support is now included in https://github.com/jonhoo/msql-srv/pull/27
