### ISSUE TITLE
Any documentation for the architecture?

### ISSUE THREAD

**Issue by ruipacheco** [jonhoo/msql-srv#29]
Hello,

I'm trying to implement something similar for PostgreSQL but am unsure of how to go about doing it. Is there any documentation for the architecture? What patterns did you use, any other projects you use for inspiration?

**Comment by jonhoo** [comment]
Hi there! No, I don't have any design docs for this unfortunately. It mostly fell out of implementing the protocol while abstracting over the connection type. There are definitely some things that I think in retrospect I would change (like I wouldn't split the `Read` and the `Write` halves of the connection), but ultimately I don't think the internal architecture is super novel or interesting.

Best of luck!
