### ISSUE TITLE
let shims know about USE schema commands

### ISSUE THREAD

**Issue by jbmcgill** [jonhoo/msql-srv#5]
It would be useful for the shims to be notified of the client issuing a 0x02 COM_INIT_DB / Command::Init(&'a [u8]). This command is sent by users on the mysql client to switch the connection context to another schema.

Currently this command is handled in lib.rs by sending the OK packet without notifying the shim.

A potential solution is to add on_init_db(&mut self, schema: &str) to the MysqlShim trait.

This would impact users of this package.

Would you consider accepting a contribution for this?

**Comment by jonhoo** [comment]
Ah, yes, that seems like a good change! I think I would add that method to the trait but with a default implementation of `{}` so that the change remains backwards compatible :)
