### ISSUE TITLE
Multiple rows throws error from select query

### ISSUE THREAD

**Issue by rnbguy** [jonhoo/msql-srv#8]
When a select returns multiple rows, it throws "row has fewer columns than specification" !

I am following your postgresql example.

**Comment by rnbguy** [comment]
It looks like, I have to call `end_row()` between each row. It is not there at the end of this loop

https://github.com/jonhoo/msql-srv/blob/5fd1c7573842a94a2bc5be170c771a30118cc250/examples/psql_as_mysql.rs#L267-L287

It should have a `writer.end_row()?;` after line 286.

**Comment by jonhoo** [comment]
Ah, yes, I think you're right! Could you submit a PR?
